version: 2.1
orbs:
  continuation: circleci/continuation@1.0
  node: circleci/node@5.2
setup: true
jobs:
  generate-config:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Generate config
          command: npm ci && npm start
          working_directory: .circleci/dynamic
      - continuation/continue:
          configuration_path: .circleci/dynamic/dynamicConfig.yml
workflows:
  dynamic-workflow:
    jobs:
      - generate-config
