version: 2.1

executors:
  default-executor:
    docker:
      - image: cypress/base:10

jobs:
  set-up-dependencies:
    executor: default-executor
    steps:
      - run: git clone --depth 1 --verbose $CIRCLE_REPOSITORY_URL

      - restore_cache:
          keys:
            - v2-deps-{{ checksum "package-lock.json" }}
            - v2-deps

      - run:
          name: 'Install dependencies'
          command: npm ci

      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: v2-deps-{{ checksum "package-lock.json" }}

      - persist_to_workspace:
          root: .
          paths: .

  run-prettier:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run prettier check on project files'
          command: npm run prettier:check
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package-lock.json" }}

  run-linter:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run linter'
          command: npm run lint

  run-unit-tests:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Run unit tests'
          command: npm run test:unit

  e2e-tests:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "package-lock.json" }}
            - v2-deps
            - node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: 'Run e2e tests'
          command: npm run test:e2e:headless

  build:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Build'
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: .

  verify-bundles-sizes:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Check bundles sizes'
          command: npm run bundlesize

  deploy:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Firebase deploy'
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]
              then
              npm run firebase:deploy:ci
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - set-up-dependencies
      - run-prettier:
          requires:
            - set-up-dependencies
      - run-linter:
          requires:
            - set-up-dependencies
      - run-unit-tests:
          requires:
            - set-up-dependencies
      - e2e-tests:
          requires:
            - set-up-dependencies
      - build:
          requires:
            - run-prettier
            - run-linter
            - run-unit-tests
            - e2e-tests
      - verify-bundles-sizes:
          requires:
            - build
      - deploy:
          requires:
            - verify-bundles-sizes
