version: 2.1
setup: true
jobs:
  set-up-config:
    executor: continuation/default
    steps:
      - run:
          name: Ensure volume is writable
          command: >-
            if [ "$(ls -ld /tmp/local-ci | awk '{print $3}')" != "$(whoami)" ] && [ "$(sudo -V 2>/dev/null)" ]
              then
              sudo chown $(whoami) /tmp/local-ci
            fi
      - run:
          name: Set more environment variables
          command: >-
            echo 'echo "export CIRCLE_SHA1=037f2d35d59080dc313608c565b55f37d2f42c7e"
            echo "export CIRCLE_BRANCH=develop"
            echo "export CIRCLE_PROJECT_REPONAME=local-ci"
            echo "export CIRCLE_REPOSITORY_URL=git@github.com:getlocalci/local-ci.git"' >> $BASH_ENV
      - checkout
      - run:
          name: Create config
          command: echo "Creating the dynamic config here"
          environment:
            BASE_REVISION: main
            MAPPING: |
              .*\.php$ run-php true
              .*\.js$ run-js true
              .*\.(php|js|json|yml)$ run-e2e true
            OUTPUT_PATH: /tmp/pipeline-parameters.json
      - run:
          name: Continue the pipeline
          command: |-
            if [ -e /tmp/local-ci/dynamic-config.yml ]
            then
              rm /tmp/local-ci/dynamic-config.yml
            fi
            cp .circleci/continue_config.yml /tmp/local-ci/dynamic-config.yml
            if [ -e /tmp/pipeline-parameters.json ]
            then
              cp /tmp/pipeline-parameters.json /tmp/local-ci/dynamic-config-parameters.json
            fi
workflows:
  setup:
    jobs:
      - set-up-config
